cache:
  directories:
    - $HOME/.composer/cache

language: php
php:
  - 5.6
  - 7.0
services:
  - docker
sudo: required

env:
  global:
    - PACKAGECLOUD_REPO=layershifter/php-gumbo
    - PRODUCT=php-gumbo
  matrix:
    - OS=debian DIST=jessie PACK=deb
    - PACK=none

matrix:
  exclude:
    - env: OS=debian DIST=jessie PACK=deb
      php: 7

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - git clone https://github.com/tarantool/build.git
  - bash travis/build.sh
  - if [[ $PACK == 'none' && $TRAVIS_PHP_VERSION != '7.0' ]]; then vendor/bin/phpunit; fi

notifications:
  email: false
  irc: false