cache:
  directories:
    - $HOME/.composer/cache

language: php
php:
  - 5.6
  - 7.0
services:
  - docker
sudo: required

env:
  global:
    - PRODUCT=php-gumbo
  matrix:
#    - OS=debian DIST=jessie PACK=deb
    - PACK=none

#matrix:
#  fast_finish: true
#  exclude:
#    - env: OS=debian DIST=jessie PACK=deb
#      php: 7

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - git clone https://github.com/tarantool/build.git
  - bash build/pack/travis.sh
  - vendor/bin/phpunit

notifications:
  email: false
  irc: false